name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev shfmt
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Setup virtualenv
        run: |
          python -m venv .venv
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: pip install maturin black
      - name: Format
        run: make fmt
      - name: Install
        run: make install
